// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: product.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Product) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ProductMultiError, or nil if none found.
func (m *Product) ValidateAll() error {
	return m.validate(true)
}

func (m *Product) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Inventory

	if len(errors) > 0 {
		return ProductMultiError(errors)
	}

	return nil
}

// ProductMultiError is an error wrapping multiple validation errors returned
// by Product.ValidateAll() if the designated constraints aren't met.
type ProductMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductMultiError) AllErrors() []error { return m }

// ProductValidationError is the validation error returned by Product.Validate
// if the designated constraints aren't met.
type ProductValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductValidationError) ErrorName() string { return "ProductValidationError" }

// Error satisfies the builtin error interface
func (e ProductValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProduct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductValidationError{}

// Validate checks the field values on NewProduct with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NewProduct) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewProduct with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NewProductMultiError, or
// nil if none found.
func (m *NewProduct) ValidateAll() error {
	return m.validate(true)
}

func (m *NewProduct) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Inventory

	if len(errors) > 0 {
		return NewProductMultiError(errors)
	}

	return nil
}

// NewProductMultiError is an error wrapping multiple validation errors
// returned by NewProduct.ValidateAll() if the designated constraints aren't met.
type NewProductMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewProductMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewProductMultiError) AllErrors() []error { return m }

// NewProductValidationError is the validation error returned by
// NewProduct.Validate if the designated constraints aren't met.
type NewProductValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewProductValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewProductValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewProductValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewProductValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewProductValidationError) ErrorName() string { return "NewProductValidationError" }

// Error satisfies the builtin error interface
func (e NewProductValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewProduct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewProductValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewProductValidationError{}

// Validate checks the field values on ProductId with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProductId) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductId with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProductIdMultiError, or nil
// if none found.
func (m *ProductId) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductId) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return ProductIdMultiError(errors)
	}

	return nil
}

// ProductIdMultiError is an error wrapping multiple validation errors returned
// by ProductId.ValidateAll() if the designated constraints aren't met.
type ProductIdMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductIdMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductIdMultiError) AllErrors() []error { return m }

// ProductIdValidationError is the validation error returned by
// ProductId.Validate if the designated constraints aren't met.
type ProductIdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductIdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductIdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductIdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductIdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductIdValidationError) ErrorName() string { return "ProductIdValidationError" }

// Error satisfies the builtin error interface
func (e ProductIdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductIdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductIdValidationError{}

// Validate checks the field values on ProductSearchRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProductSearchRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductSearchRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProductSearchRequestMultiError, or nil if none found.
func (m *ProductSearchRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductSearchRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if len(errors) > 0 {
		return ProductSearchRequestMultiError(errors)
	}

	return nil
}

// ProductSearchRequestMultiError is an error wrapping multiple validation
// errors returned by ProductSearchRequest.ValidateAll() if the designated
// constraints aren't met.
type ProductSearchRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductSearchRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductSearchRequestMultiError) AllErrors() []error { return m }

// ProductSearchRequestValidationError is the validation error returned by
// ProductSearchRequest.Validate if the designated constraints aren't met.
type ProductSearchRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductSearchRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductSearchRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductSearchRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductSearchRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductSearchRequestValidationError) ErrorName() string {
	return "ProductSearchRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProductSearchRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductSearchRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductSearchRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductSearchRequestValidationError{}

// Validate checks the field values on ProductListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProductListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProductListResponseMultiError, or nil if none found.
func (m *ProductListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProducts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProductListResponseValidationError{
						field:  fmt.Sprintf("Products[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProductListResponseValidationError{
						field:  fmt.Sprintf("Products[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProductListResponseValidationError{
					field:  fmt.Sprintf("Products[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProductListResponseMultiError(errors)
	}

	return nil
}

// ProductListResponseMultiError is an error wrapping multiple validation
// errors returned by ProductListResponse.ValidateAll() if the designated
// constraints aren't met.
type ProductListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductListResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductListResponseMultiError) AllErrors() []error { return m }

// ProductListResponseValidationError is the validation error returned by
// ProductListResponse.Validate if the designated constraints aren't met.
type ProductListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductListResponseValidationError) ErrorName() string {
	return "ProductListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ProductListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductListResponseValidationError{}

// Validate checks the field values on ProductResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProductResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProductResponseMultiError, or nil if none found.
func (m *ProductResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return ProductResponseMultiError(errors)
	}

	return nil
}

// ProductResponseMultiError is an error wrapping multiple validation errors
// returned by ProductResponse.ValidateAll() if the designated constraints
// aren't met.
type ProductResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductResponseMultiError) AllErrors() []error { return m }

// ProductResponseValidationError is the validation error returned by
// ProductResponse.Validate if the designated constraints aren't met.
type ProductResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductResponseValidationError) ErrorName() string { return "ProductResponseValidationError" }

// Error satisfies the builtin error interface
func (e ProductResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductResponseValidationError{}
