// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto_files/bff.proto

package proto_files

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FindAvailableProductsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FindAvailableProductsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FindAvailableProductsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FindAvailableProductsRequestMultiError, or nil if none found.
func (m *FindAvailableProductsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FindAvailableProductsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := ProductType_name[int32(m.GetType())]; !ok {
		err := FindAvailableProductsRequestValidationError{
			field:  "Type",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPageSize() <= 0 {
		err := FindAvailableProductsRequestValidationError{
			field:  "PageSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FindAvailableProductsRequestMultiError(errors)
	}

	return nil
}

// FindAvailableProductsRequestMultiError is an error wrapping multiple
// validation errors returned by FindAvailableProductsRequest.ValidateAll() if
// the designated constraints aren't met.
type FindAvailableProductsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FindAvailableProductsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FindAvailableProductsRequestMultiError) AllErrors() []error { return m }

// FindAvailableProductsRequestValidationError is the validation error returned
// by FindAvailableProductsRequest.Validate if the designated constraints
// aren't met.
type FindAvailableProductsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindAvailableProductsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindAvailableProductsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindAvailableProductsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindAvailableProductsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FindAvailableProductsRequestValidationError) ErrorName() string {
	return "FindAvailableProductsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FindAvailableProductsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindAvailableProductsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindAvailableProductsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindAvailableProductsRequestValidationError{}

// Validate checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Product) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ProductMultiError, or nil if none found.
func (m *Product) ValidateAll() error {
	return m.validate(true)
}

func (m *Product) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := ProductValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := ProductValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := ProductType_name[int32(m.GetType())]; !ok {
		err := ProductValidationError{
			field:  "Type",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetInventory() < 0 {
		err := ProductValidationError{
			field:  "Inventory",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProductMultiError(errors)
	}

	return nil
}

// ProductMultiError is an error wrapping multiple validation errors returned
// by Product.ValidateAll() if the designated constraints aren't met.
type ProductMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductMultiError) AllErrors() []error { return m }

// ProductValidationError is the validation error returned by Product.Validate
// if the designated constraints aren't met.
type ProductValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductValidationError) ErrorName() string { return "ProductValidationError" }

// Error satisfies the builtin error interface
func (e ProductValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProduct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductValidationError{}

// Validate checks the field values on ProductListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProductListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProductListResponseMultiError, or nil if none found.
func (m *ProductListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProducts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProductListResponseValidationError{
						field:  fmt.Sprintf("Products[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProductListResponseValidationError{
						field:  fmt.Sprintf("Products[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProductListResponseValidationError{
					field:  fmt.Sprintf("Products[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProductListResponseMultiError(errors)
	}

	return nil
}

// ProductListResponseMultiError is an error wrapping multiple validation
// errors returned by ProductListResponse.ValidateAll() if the designated
// constraints aren't met.
type ProductListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductListResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductListResponseMultiError) AllErrors() []error { return m }

// ProductListResponseValidationError is the validation error returned by
// ProductListResponse.Validate if the designated constraints aren't met.
type ProductListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductListResponseValidationError) ErrorName() string {
	return "ProductListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ProductListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductListResponseValidationError{}

// Validate checks the field values on NewOrder with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NewOrder) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewOrder with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NewOrderMultiError, or nil
// if none found.
func (m *NewOrder) ValidateAll() error {
	return m.validate(true)
}

func (m *NewOrder) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductId() <= 0 {
		err := NewOrderValidationError{
			field:  "ProductId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetCount(); val < 2 || val > 100 {
		err := NewOrderValidationError{
			field:  "Count",
			reason: "value must be inside range [2, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return NewOrderMultiError(errors)
	}

	return nil
}

// NewOrderMultiError is an error wrapping multiple validation errors returned
// by NewOrder.ValidateAll() if the designated constraints aren't met.
type NewOrderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewOrderMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewOrderMultiError) AllErrors() []error { return m }

// NewOrderValidationError is the validation error returned by
// NewOrder.Validate if the designated constraints aren't met.
type NewOrderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewOrderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewOrderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewOrderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewOrderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewOrderValidationError) ErrorName() string { return "NewOrderValidationError" }

// Error satisfies the builtin error interface
func (e NewOrderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewOrder.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewOrderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewOrderValidationError{}

// Validate checks the field values on OrderId with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderId) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderId with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OrderIdMultiError, or nil if none found.
func (m *OrderId) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderId) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := OrderIdValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrderIdMultiError(errors)
	}

	return nil
}

// OrderIdMultiError is an error wrapping multiple validation errors returned
// by OrderId.ValidateAll() if the designated constraints aren't met.
type OrderIdMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderIdMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderIdMultiError) AllErrors() []error { return m }

// OrderIdValidationError is the validation error returned by OrderId.Validate
// if the designated constraints aren't met.
type OrderIdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderIdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderIdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderIdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderIdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderIdValidationError) ErrorName() string { return "OrderIdValidationError" }

// Error satisfies the builtin error interface
func (e OrderIdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderIdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderIdValidationError{}

// Validate checks the field values on NewProduct with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NewProduct) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewProduct with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NewProductMultiError, or
// nil if none found.
func (m *NewProduct) ValidateAll() error {
	return m.validate(true)
}

func (m *NewProduct) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 5 || l > 10 {
		err := NewProductValidationError{
			field:  "Name",
			reason: "value length must be between 5 and 10 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_NewProduct_Name_Pattern.MatchString(m.GetName()) {
		err := NewProductValidationError{
			field:  "Name",
			reason: "value does not match regex pattern \"^[A-Z]{5,10}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := ProductType_name[int32(m.GetType())]; !ok {
		err := NewProductValidationError{
			field:  "Type",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetInventory() < 0 {
		err := NewProductValidationError{
			field:  "Inventory",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return NewProductMultiError(errors)
	}

	return nil
}

// NewProductMultiError is an error wrapping multiple validation errors
// returned by NewProduct.ValidateAll() if the designated constraints aren't met.
type NewProductMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewProductMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewProductMultiError) AllErrors() []error { return m }

// NewProductValidationError is the validation error returned by
// NewProduct.Validate if the designated constraints aren't met.
type NewProductValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewProductValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewProductValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewProductValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewProductValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewProductValidationError) ErrorName() string { return "NewProductValidationError" }

// Error satisfies the builtin error interface
func (e NewProductValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewProduct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewProductValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewProductValidationError{}

var _NewProduct_Name_Pattern = regexp.MustCompile("^[A-Z]{5,10}$")

// Validate checks the field values on ProductId with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProductId) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductId with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProductIdMultiError, or nil
// if none found.
func (m *ProductId) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductId) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := ProductIdValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProductIdMultiError(errors)
	}

	return nil
}

// ProductIdMultiError is an error wrapping multiple validation errors returned
// by ProductId.ValidateAll() if the designated constraints aren't met.
type ProductIdMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductIdMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductIdMultiError) AllErrors() []error { return m }

// ProductIdValidationError is the validation error returned by
// ProductId.Validate if the designated constraints aren't met.
type ProductIdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductIdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductIdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductIdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductIdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductIdValidationError) ErrorName() string { return "ProductIdValidationError" }

// Error satisfies the builtin error interface
func (e ProductIdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductIdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductIdValidationError{}
