name: Build GoLang Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      
    runs-on: ${{matrix.os}}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          lfs: 'true'

      - name: Buf CLI
        uses: bufbuild/buf-setup-action@v1.34.0
        with:
          github_token: ${{ github.token }}
      - run: buf --version

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.22.5'
      
      - name: Go Tidy
        run: go mod tidy
      
      - name: Install dependencies
        run: |
          go mod download
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      
      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
          wait: true

      - name: start dockerized tests
        run: go test contract_test.go -v -count=1
