name: Build GoLang Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      
    runs-on: ${{matrix.os}}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          lfs: 'true'

      - name: Buf CLI
        uses: bufbuild/buf-setup-action@v1.34.0
        with:
          github_token: ${{ github.token }}
      - run: buf --version

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.22.5'
      
      - name: Go Tidy
        run: go mod tidy
      
      - name: Install dependencies
        run: |
          go mod download
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      
      - name: setup env
        run: 
          echo "$GOPATH/bin" >> $GITHUB_PATH
      
      - name: Build with Makefile
        run: make all
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java --version

      - name: Start gRPC Stub
        run: java --version && java -jar lib/specmatic-grpc-0.0.2-TRIAL-all.jar stub &

      - name: Start Golang gRPC Server
        run: ./specmatic-order-bff-grpc-go &
      
      - name: Start gRPC Contract Test
        run: java -DSPECMATIC_GENERATIVE_TESTS=true -jar lib/specmatic-grpc-0.0.2-TRIAL-all.jar test --port 50051
